language: go

go:
  - 1.4
  - 1.3
  - 1.2

install:
  - go get github.com/acsellers/inflections
  - go get github.com/mattn/go-sqlite3
  - go get github.com/codegangsta/cli
  - go get golang.org/x/tools/imports
  - go install github.com/acsellers/dr

script:
  - cd example/blog
  - dr build
  - go test
